version: 1.2
workflows:
   - name: GATK-For-Primates-on-Terra
     subclass: WDL
     primaryDescriptorPath: /terra-wrapper.wdl
     authors:
       - name: Graham L Banes
         orcid: https://orcid.org/0000-0003-4382-7684
         email: banes@wisc.edu
         affiliation: Wisconsin National Primate Research Center, University of Wisconsin-Madison
       - name: Bhanu Gandham
         email: bgandham@broadinstitute.org
         affiliation: Broad Institute
