version: 1.2
workflows:
   - name: GATK-For-Primates-on-Terra
     subclass: WDL
     primaryDescriptorPath: /terra-runner.wdl
     testParameterFiles:
     -  /example_inputs/example_inputs_terra_initial.json
        /example_inputs/example_inputs_terra_repeat.json
        /example_inputs/example_inputs_terra_final_no_truth_sets.json
     authors:
       - name: Graham L Banes
         orcid: https://orcid.org/0000-0003-4382-7684
         email: banes@wisc.edu
         affiliation: Wisconsin National Primate Research Center, University of Wisconsin-Madison
       - name: Bhanu Gandham
         email: bgandham@broadinstitute.org
         affiliation: Broad Institute
