version: 1.2
workflows:
   - name: GATK-For-Primates
     subclass: WDL
     primaryDescriptorPath: /gatk-for-primates-germline-snps-indels.wdl
     testParameterFiles:
     -  /example_inputs_initial.json
        /example_inputs_initial_bam.json
        /example_inputs_repeat.json
        /example_inputs_repeat_bam.json
        /example_inputs_final_no_truth_sets.json
     authors:
       - name: Graham L Banes
         orcid: https://orcid.org/0000-0003-4382-7684
         email: banes@wisc.edu
         affiliation: Wisconsin National Primate Research Center, University of Wisconsin-Madison
       - name: Bhanu Gandham
         email: bgandham@broadinstitute.org
         affiliation: Broad Institute
